build:
  image: node:14.15
  stage: build
  only:
    - development
  script:
    - npm install --progress=false
    - npm run build

deploy:
  stage: deploy
  only:
    - development
  script:
    - docker build --no-cache -t $PROJECT_NAME . && docker stop $PROJECT_NAME || true && docker rm $PROJECT_NAME || true && docker run -d -p 8082:8082 --restart=always --name $PROJECT_NAME $PROJECT_NAME
