build:
  image: node:14
  stage: build
  only:
    - master
  script:
    - npm install --progress=false
    - npm run build

deploy:
  image: alpine
  stage: deploy
  only:
    - master
  script: -apk update
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.sshну
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/known_hosts
    - ssh-keyscan "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete ./ root@"$SSH_KNOWN_HOSTS":"$SSH_DIR"
    - ssh -t root@"$SSH_KNOWN_HOSTS" "cd $SSH_DIR && docker build --no-cache -t $PROJECT_NAME . && docker stop $PROJECT_NAME || true && docker rm $PROJE
